//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakka.Pos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fakka.Pos.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned products list.
        /// </summary>
        public static string BannedProductsList {
            get {
                return ResourceManager.GetString("BannedProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payment.
        /// </summary>
        public static string CashPayment {
            get {
                return ResourceManager.GetString("CashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not selected additional items! this student has an online order set..
        /// </summary>
        public static string ChildHasOnlineOrderErrorMessage {
            get {
                return ResourceManager.GetString("ChildHasOnlineOrderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code number.
        /// </summary>
        public static string CodeNumber {
            get {
                return ResourceManager.GetString("CodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily limit.
        /// </summary>
        public static string DailyLimit {
            get {
                return ResourceManager.GetString("DailyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full POS.
        /// </summary>
        public static string FullPos {
            get {
                return ResourceManager.GetString("FullPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading products.
        /// </summary>
        public static string LoadingProducts {
            get {
                return ResourceManager.GetString("LoadingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make transaction.
        /// </summary>
        public static string MakeTransaction {
            get {
                return ResourceManager.GetString("MakeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the name first.
        /// </summary>
        public static string NameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No children were found using your search parameters.
        /// </summary>
        public static string NoChildrenFoundSearching {
            get {
                return ResourceManager.GetString("NoChildrenFoundSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There no Bluetooth device in the area, or make sure that your device is connected to Bluetooth.
        /// </summary>
        public static string NoConnectedBluetooth {
            get {
                return ResourceManager.GetString("NoConnectedBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or search with code.
        /// </summary>
        public static string OrSearchWithCode {
            get {
                return ResourceManager.GetString("OrSearchWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or search with name.
        /// </summary>
        public static string OrSearchWithName {
            get {
                return ResourceManager.GetString("OrSearchWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry this product is banned!.
        /// </summary>
        public static string ProductBannedMessage {
            get {
                return ResourceManager.GetString("ProductBannedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryial.
        /// </summary>
        public static string Ryial {
            get {
                return ResourceManager.GetString("Ryial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with code.
        /// </summary>
        public static string SearchWithCode {
            get {
                return ResourceManager.GetString("SearchWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with name.
        /// </summary>
        public static string SearchWithName {
            get {
                return ResourceManager.GetString("SearchWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a grade!.
        /// </summary>
        public static string SelectGradeMessage {
            get {
                return ResourceManager.GetString("SelectGradeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple POS.
        /// </summary>
        public static string SimplePos {
            get {
                return ResourceManager.GetString("SimplePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SAR.
        /// </summary>
        public static string StockItemPrice {
            get {
                return ResourceManager.GetString("StockItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Unit.
        /// </summary>
        public static string StockItemQty {
            get {
                return ResourceManager.GetString("StockItemQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student code.
        /// </summary>
        public static string StudentCode {
            get {
                return ResourceManager.GetString("StudentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a student first.
        /// </summary>
        public static string StudentNotSelected {
            get {
                return ResourceManager.GetString("StudentNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student name.
        /// </summary>
        public static string StundentName {
            get {
                return ResourceManager.GetString("StundentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s orders ({0}).
        /// </summary>
        public static string TodaysOrders {
            get {
                return ResourceManager.GetString("TodaysOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction completed successfully.
        /// </summary>
        public static string TransactionCompleted {
            get {
                return ResourceManager.GetString("TransactionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
